# Generated by Django 4.2.7 on 2025-12-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_create_default_statuses'),
        ('projects', '0002_rename_vector_sum_to_sum'),
    ]

    operations = [
    ]
