# Generated by Django 4.2.7 on 2025-12-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_merge_20251217_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sum',
            field=models.FloatField(default=0.0, verbose_name='Сумма'),
        ),
    ]
