# Generated by Django 4.2.7 on 2025-12-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_rename_vector_sum_to_sum'),
        ('evaluations', '0003_remove_llm_generated_fields'),
    ]

    operations = [
    ]
