# Generated by Django 4.2.7 on 2025-12-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_merge_20251217_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevaluation',
            name='sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
